version: '3.2'
    
services:
  python:
    image: indexnet/python:1.0
    build: ./python
    container_name: 'indexnet_python'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes:
      - ~/dockerenv/indexnet_matting_sample:/tmp/work